baseurl: "https://tabularconf.es"
title: "Conference name"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""




params:
  # Conference info
  Title: "TabularConf"
  Name: "Tabular"
  Extraname: "Conf"
  Description: "On the edge of datascience"
  Date: "30 de Enero 2021"
  #Price: "Only $100" # If your event is free, just comment this line
  #Twitter: "@prueba"
  Venue: "2020"
  #Address: "Boulevard Kukulcan, 30"
  City:  "Online"
  #State: "Online"
  Images: ["/img/bg.jpeg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - topic
    - location
    - speakers
    - schedule
    #- sponsors
    - partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "Evento"
    topics: "CoC"
    location: "FAQ"
    speakers: "Ponentes"
    schedule: "Agenda"
    sponsors: "Sponsors"
    partners: "Organiza"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #CallToAction:
  #  text: "Register now!"
  #  link: "http://register.example.com"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Hugo"
      logo: "/img/hugo.png"
      url: "http://gohugo.io"

  # List of Partners
  Partners:
    - name: "Python España"
      logo: "/img/python_es.png"
      url: "https://es.python.org/"
    - name: "Python Canarias"
      logo: "/img/logo-python-canarias-color.svg"
      url: "https://pythoncanarias.es/"
    - name: "R Canarias"
      logo: "/img/logo_R_Canarias.jpg"
      url: "http://canarias.r-es.org/"
    - name: "PyData Salamanca"
      logo: "/img/pydata-sal-logo.png"
      url: "https://www.meetup.com/es-ES/PyData-Salamanca/"
    - name: "RLadies Madrid"
      logo: "/img/rladies.png"
      url: "https://www.meetup.com/es/rladies-madrid/"
  
    - name: "Python Málaga"
      logo: "/img/python_malaga.png"
      url: "https://www.python-malaga.es/"
  


  # The entire schedule
  Schedule: 
    - name: "Masajeando datos: ETLs en la nube con Data Fusion"
      photo: 
      bio: 
      company: 
      link:
        href:
        text:
      presentation:
        title:
        description:
        time: 

    - name: "Dime cómo juegas y me adaptaré a quién eres"
      time: "10h30"
    - name: "La luna deja un histograma abandonado en el aire"
      time: "11h00"
    - name: "Aplicaciones del Machine Learning al mundo del fútbol"
      time: "11h30"
    - name: "Identifica a tu mascota con Computer Vision"
      time: "12h00"
    - name: "Mitigating Eviction Risk for Residents in the City of Dallas"
      time: "12h30"
    - name: "Ciencia de datos geoespaciales para la vigilancia de la salud pública - KEYNOTE"
      time: "13h00"
    - name: "MLOps: cómo poner tus sistemas de machine learning en producción"
      time: "13h30"
    - name: "TBD"
      time: "14h00"